name: LINE Reminder to 次回の予定

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 28 * *"

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r post-remind-to-line-monthly-reminder/requirements.txt

      - name: Run post-remind-to-line-monthly-reminder/main.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
        run: python post-remind-to-line-monthly-reminder/main.py
